// Generated by npm run build from src/index.ts. Do not edit directly.

// src/index.ts
import { tool } from "@opencode-ai/plugin";
import { resolve as resolve2 } from "node:path";

// src/blueprint.ts
import { execFile } from "node:child_process";
import { basename, dirname, resolve } from "node:path";
import { promisify } from "node:util";
var execFileAsync = promisify(execFile);
function isBlueprintFile(filePath) {
  const name = basename(filePath);
  return name === "render.yaml" || name === "render.yml";
}
async function validateBlueprint(filePath, directory = process.cwd(), signal) {
  const path = resolve(directory, filePath);
  const cwd = dirname(path);
  const command = `render blueprints validate ${JSON.stringify(path)} --output json`;
  try {
    const result = await execFileAsync("render", ["blueprints", "validate", path, "--output", "json"], {
      cwd,
      signal,
      timeout: 3e4
    });
    const output = [result.stdout, result.stderr].filter(Boolean).join("\n").trim();
    return {
      ok: true,
      command,
      cwd,
      output: output || "render blueprints validate completed successfully."
    };
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return {
        ok: false,
        command,
        cwd,
        output: "Render CLI not found. Install it to validate render.yaml:\n  macOS:  brew install render\n  Linux:  curl -fsSL https://raw.githubusercontent.com/render-oss/cli/main/bin/install.sh | sh",
        error: "render-cli-not-found"
      };
    }
    const output = getExecErrorOutput(error);
    return {
      ok: false,
      command,
      cwd,
      output: output || String(error),
      error: "validation-failed"
    };
  }
}
function getExecErrorOutput(error) {
  if (typeof error === "object" && error !== null) {
    const withOutput = error;
    return [withOutput.stdout, withOutput.stderr, withOutput.message].filter((value) => typeof value === "string" && value.length > 0).join("\n").trim();
  }
  return "";
}
function isNodeError(error) {
  return typeof error === "object" && error !== null && "code" in error;
}

// src/touched-files.ts
var FILE_PATH_KEYS = /* @__PURE__ */ new Set(["file", "filePath", "file_path", "filename", "path"]);
var MUTATING_TOOLS = /* @__PURE__ */ new Set(["write", "edit", "multiedit", "apply_patch"]);
function extractMutatedFiles(tool2, args, metadata) {
  if (!MUTATING_TOOLS.has(tool2)) return [];
  if (tool2 !== "apply_patch") return [...new Set(extractTouchedFiles(args))];
  if (isRecord(metadata) && Array.isArray(metadata.files)) {
    return [...new Set(metadata.files.flatMap((file) => {
      if (!isRecord(file) || file.type === "delete") return [];
      const path = file.movePath ?? file.filePath;
      return typeof path === "string" ? [path] : [];
    }))];
  }
  if (!isRecord(args) || typeof args.patchText !== "string") return [];
  const files = [];
  for (const line of args.patchText.split(/\r?\n/)) {
    const match = /^\*\*\* (Add File|Update File|Move to): (.+)$/.exec(line);
    if (!match) continue;
    if (match[1] === "Move to") files.pop();
    files.push(match[2]);
  }
  return [...new Set(files)];
}
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function extractTouchedFiles(value) {
  const files = [];
  collectTouchedFiles(value, files);
  return files;
}
function collectTouchedFiles(value, files, key) {
  if (typeof value === "string") {
    if (key && FILE_PATH_KEYS.has(key)) {
      files.push(value);
    }
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      collectTouchedFiles(item, files);
    }
    return;
  }
  if (typeof value !== "object" || value === null) {
    return;
  }
  for (const [entryKey, entryValue] of Object.entries(value)) {
    collectTouchedFiles(entryValue, files, entryKey);
  }
}

// src/index.ts
var RenderPlugin = async ({ client, directory }) => {
  await client.app.log({
    body: {
      service: "render-opencode-plugin",
      level: "info",
      message: "Render OpenCode plugin initialized"
    }
  });
  return {
    tool: {
      render_validate_blueprint: tool({
        description: "Validate a Render Blueprint file with the Render CLI.",
        args: {
          path: tool.schema.string().describe("Path to render.yaml or render.yml.")
        },
        async execute(args, context) {
          const result = await validateBlueprint(args.path, context.directory, context.abort);
          return {
            title: result.ok ? "Render Blueprint valid" : "Render Blueprint validation failed",
            output: result.output,
            metadata: {
              command: result.command,
              cwd: result.cwd,
              ok: result.ok,
              error: result.error
            }
          };
        }
      })
    },
    "tool.execute.after": async (input, output) => {
      const paths = [...new Set(extractMutatedFiles(input.tool, input.args, output.metadata).filter(isBlueprintFile).map((path) => resolve2(directory, path)))];
      const failures = [];
      for (const path of paths) {
        const result = await validateBlueprint(path, directory);
        if (!result.ok) {
          failures.push({ path, ...result });
          continue;
        }
        await client.app.log({ body: {
          service: "render-opencode-plugin",
          level: "info",
          message: "Validated Render Blueprint",
          extra: { path, cwd: result.cwd }
        } });
      }
      if (failures.length === 0) return;
      output.title = "Render Blueprint validation";
      output.output = [output.output, ...failures.map((result) => `${result.path}
${result.output}`)].filter(Boolean).join("\n\n");
      output.metadata = {
        ...output.metadata,
        renderBlueprintValidation: {
          ok: false,
          command: failures[0].command,
          cwd: failures[0].cwd,
          error: failures[0].error,
          results: failures
        }
      };
    }
  };
};
var index_default = RenderPlugin;
export {
  RenderPlugin,
  index_default as default
};
