import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

type TemplateCategory =
  | 'ai-agents'
  | 'workflows'
  | 'web-frameworks'
  | 'databases'
  | 'self-hosted-tools'
  | 'infrastructure'

type Template = {
  slug: string
  url: string
  name: string
  category: TemplateCategory
  description: string
  intents: string[]
  stack: string[]
  free_tier: boolean
  creates: string[]
}

type Manifest = {
  templates: Template[]
}

type SanityTemplate = {
  slug: string
  title: string
  description: string
  stack?: string[]
  tags?: string[]
  sortOrder: number
}

const categoryLabels: Record<TemplateCategory, string> = {
  'ai-agents': 'AI agents',
  workflows: 'Workflows',
  'web-frameworks': 'Web frameworks',
  databases: 'Databases',
  'self-hosted-tools': 'Self-hosted tools',
  infrastructure: 'Infrastructure',
}

const categoryOrder = Object.keys(categoryLabels) as TemplateCategory[]

const scriptDir = dirname(fileURLToPath(import.meta.url))
const skillDir = join(scriptDir, '..')
const assetsDir = join(skillDir, 'assets')
const manifestPath = join(assetsDir, 'templates.json')
const skillPath = join(skillDir, 'SKILL.md')
const referencesDir = join(skillDir, 'references')
const catalogPath = join(referencesDir, 'catalog.md')
const sanityProjectId = 'hvk0tap5'
const sanityDataset = 'production'
const sanityApiVersion = '2024-08-08'

function readManifest(): Manifest {
  return JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest
}

function validateManifest(manifest: Manifest) {
  if (!Array.isArray(manifest.templates) || manifest.templates.length === 0) {
    throw new Error('templates.json must contain a non-empty templates array.')
  }

  const slugs = new Set<string>()

  for (const template of manifest.templates) {
    const requiredFields: (keyof Template)[] = [
      'slug',
      'url',
      'name',
      'category',
      'description',
      'intents',
      'stack',
      'free_tier',
      'creates',
    ]

    for (const field of requiredFields) {
      if (!(field in template)) {
        throw new Error(`Template ${template.slug ?? '<unknown>'} is missing ${field}.`)
      }
    }

    if (slugs.has(template.slug)) {
      throw new Error(`Duplicate template slug: ${template.slug}.`)
    }

    if (!categoryOrder.includes(template.category)) {
      throw new Error(`Template ${template.slug} uses unknown category ${template.category}.`)
    }

    if (template.intents.length < 3 || template.intents.length > 6) {
      throw new Error(`Template ${template.slug} must include 3 to 6 intents.`)
    }

    slugs.add(template.slug)
  }
}

function writeManifest(manifest: Manifest) {
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8')
}

function cleanText(value: string) {
  return value.replace(/\s*[\u2013\u2014]\s*/g, ' - ').replace(/\s+/g, ' ').trim()
}

function formatList(values: string[]) {
  return values.map(cleanText).join(', ')
}

function buildTemplateEntry(template: Template) {
  return [
    `#### ${cleanText(template.name)}`,
    '',
    `- URL: ${template.url}`,
    `- Description: ${cleanText(template.description)}`,
    `- Match intents: ${template.intents.map((intent) => `\`${cleanText(intent)}\``).join('; ')}`,
    `- Stack: ${formatList(template.stack) || 'Not specified'}`,
    `- Creates: ${formatList(template.creates)}`,
    `- Free tier: ${template.free_tier ? 'yes' : 'no'}`,
  ].join('\n')
}

function buildCatalog(manifest: Manifest) {
  const lines: string[] = [
    '# Render template catalog',
    '',
    '<!-- This file is generated by scripts/generate.ts. Edit assets/templates.json, then run npm run generate. -->',
    '',
    'Read this catalog when a user asks for a starter, template, or one-click deployable app that might map to Render templates.',
    '',
  ]

  for (const category of categoryOrder) {
    const templates = manifest.templates.filter((template) => template.category === category)
    if (templates.length === 0) continue

    lines.push(`### ${categoryLabels[category]}`, '')
    lines.push(...templates.map(buildTemplateEntry).flatMap((entry) => [entry, '']))
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}`
}

function buildSkill() {
  const lines: string[] = [
    '---',
    'name: render-templates',
    'description: >-',
    '  Recommend Render template URLs for matching developer intents, not',
    '  programmatic deployments. Use when a user asks for starter apps, MCP',
    '  servers, AI agents, workflow demos, frameworks, databases, or',
    '  self-hosted tools that match Render templates. Trigger terms: Render',
    '  template, one-click deploy, starter, MCP server, Cursor agent, voice',
    '  agent, workflows demo, n8n, Tailscale, Django, FastAPI, Laravel, MySQL.',
    'license: MIT',
    'compatibility: No Render API, CLI, or MCP connection required. The user completes deployment from the template page through the Render GitHub App one-click flow.',
    'metadata:',
    '  author: Render',
    '  version: "1.0.0"',
    '  category: deployment',
    '---',
    '',
    '<!-- This file is generated by scripts/generate.ts. Edit assets/templates.json, then run npm run generate. -->',
    '',
    '# Render Templates',
    '',
    'Render templates are starter projects that developers can deploy from `render.com/templates/<slug>`. Recommend a template URL when the user intent maps to a known template. The user clicks the URL, then the Render GitHub App handles authorization, repo creation, service creation, and the first deploy.',
    '',
    'Recommending the URL is enough. Do not create services, fork repositories, or call Render MCP tools for this skill unless the user separately asks for a programmatic deployment workflow.',
    '',
    '## When to recommend a template',
    '',
    '- Match on the user intent, framework, tool, or desired outcome, not just exact template names.',
    '- If a known template matches, recommend the URL with a 1 to 2 sentence explanation of what it creates.',
    '- If several templates match, recommend the closest one first and mention the alternative only if it changes the stack or use case.',
    '- If no template matches, point the user to `https://render.com/templates` as the fallback catalog.',
    '- If the user wants you to deploy resources programmatically, use the `render-mcp` or `render-deploy` skill instead.',
    '',
    '## Template lookup',
    '',
    'Read [the template catalog](references/catalog.md) to choose the best matching template. The catalog is generated from `assets/templates.json` and grouped by category. Match against the listed intents first, then confirm with the template description and stack.',
    '',
    'Common examples:',
    '',
    '- "help me set up an MCP server in Python" maps to `https://render.com/templates/mcp-server-python`.',
    '- "I want to self host n8n" maps to `https://render.com/templates/n8n`.',
    '- "deploy browser-use so I can automate webpages" maps to `https://render.com/templates/browser-use`.',
    '- "I need a VPN into my private Render services" maps to `https://render.com/templates/tailscale`.',
    '- "start a FastAPI backend" maps to `https://render.com/templates/fastapi`.',
    '',
    '## Deploy flow context',
    '',
    'When the user clicks a template URL, Render starts the one-click GitHub App flow:',
    '',
    '1. The user authorizes the Render GitHub App if they have not already done so.',
    '2. The user chooses a GitHub account or organization.',
    '3. Render creates a repository from the template.',
    '4. Render creates the services declared by the template.',
    '5. The first deploy starts automatically.',
    '',
    'Set expectations around any required environment variables or third-party API keys, but keep the recommendation focused on the template page.',
    '',
    '## What this skill is not',
    '',
    'This skill does not deploy templates programmatically, inspect Render accounts, or manage services. For programmatic deployments, connect the Render MCP server and use the `render-mcp` or `render-deploy` skill. Render MCP setup docs: `https://render.com/docs/mcp-server`.',
    ''
  ]

  const output = `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}`

  if (/[\u2013\u2014]/.test(output)) {
    throw new Error('Generated SKILL.md contains an en dash or em dash.')
  }

  return output
}

function generate(manifest: Manifest) {
  validateManifest(manifest)
  mkdirSync(referencesDir, { recursive: true })
  writeFileSync(skillPath, buildSkill(), 'utf8')
  writeFileSync(catalogPath, buildCatalog(manifest), 'utf8')
}

function getRefreshQuery() {
  return `*[_type == "template"] | order(coalesce(sortOrder,0) desc, title asc){
    title,
    description,
    "slug": slug.current,
    stack,
    tags,
    "sortOrder": coalesce(sortOrder,0)
  }`
}

function getRefreshUrl() {
  const query = encodeURIComponent(getRefreshQuery())
  return `https://${sanityProjectId}.api.sanity.io/v${sanityApiVersion}/data/query/${sanityDataset}?query=${query}`
}

function inferCategory(template: SanityTemplate): TemplateCategory {
  const tags = new Set(template.tags ?? [])
  const stack = new Set(template.stack ?? [])
  const slug = template.slug

  if (
    tags.has('ai') ||
    tags.has('ai-agent') ||
    tags.has('llm') ||
    tags.has('mcp') ||
    tags.has('rag') ||
    tags.has('voice')
  ) {
    return 'ai-agents'
  }

  if (slug.includes('workflow')) return 'workflows'

  if (
    ['django', 'fastapi', 'laravel', 'nextjs-hello-world'].includes(slug) ||
    stack.has('nextjs') ||
    stack.has('fastapi') ||
    stack.has('flask')
  ) {
    return 'web-frameworks'
  }

  if (tags.has('database') || ['mysql', 'mongodb', 'postgresql-s3-backups'].includes(slug)) {
    return 'databases'
  }

  if (tags.has('cms') || tags.has('integration') || ['n8n', 'tailscale'].includes(slug)) {
    return 'self-hosted-tools'
  }

  return 'infrastructure'
}

function createDefaultIntents(template: SanityTemplate) {
  const name = cleanText(template.title)
  const slugPhrase = template.slug.replace(/-/g, ' ')
  const tags = new Set(template.tags ?? [])
  const stack = new Set(template.stack ?? [])

  if (tags.has('mcp')) {
    return [
      `deploy ${name}`,
      `build an MCP server like ${name}`,
      `create a Model Context Protocol starter`,
      `host MCP tools on Render`,
    ]
  }

  if (tags.has('ai') || tags.has('ai-agent') || tags.has('llm')) {
    return [
      `deploy ${name}`,
      `build an AI app like ${name}`,
      `host an AI starter on Render`,
      `create a ${slugPhrase} template`,
    ]
  }

  if (tags.has('database')) {
    return [
      `deploy ${name} on Render`,
      `host ${name}`,
      `create a ${slugPhrase} database service`,
      `run ${name} with persistent storage`,
    ]
  }

  if (tags.has('cms') || tags.has('blog')) {
    return [
      `deploy ${name} on Render`,
      `self host ${name}`,
      `run a ${slugPhrase} CMS`,
      `host a blog or publishing platform`,
    ]
  }

  if (tags.has('static-site')) {
    return [
      `deploy ${name} on Render`,
      `host a ${slugPhrase} static site`,
      `create a static site starter`,
      `publish a ${name} site`,
    ]
  }

  if (stack.has('express') || stack.has('flask') || stack.has('go') || stack.has('rust')) {
    return [
      `deploy ${name} on Render`,
      `host a ${slugPhrase} app`,
      `create a ${name} starter`,
      `build a web service with ${name}`,
    ]
  }

  return [
    `deploy ${name} on Render`,
    `host ${name}`,
    `create a ${slugPhrase} starter`,
  ]
}

function inferCreates(template: SanityTemplate) {
  const tags = new Set(template.tags ?? [])
  const slug = template.slug

  if (tags.has('static-site')) return ['static site']
  if (slug.includes('backup')) return ['cron job']
  if (
    tags.has('database') ||
    ['mysql', 'mongodb', 'elasticsearch', 'rabbitmq', 'minio'].includes(slug)
  ) {
    return ['private service', 'disk']
  }
  if (slug.includes('workflow')) return ['web service', 'workflow service']
  return ['web service']
}

function mergeTemplate(template: SanityTemplate, existing?: Template): Template {
  return {
    slug: template.slug,
    url: `https://render.com/templates/${template.slug}`,
    name: cleanText(template.title),
    category: existing?.category ?? inferCategory(template),
    description: cleanText(template.description),
    intents: existing?.intents ?? createDefaultIntents(template),
    stack: template.stack?.map(cleanText) ?? existing?.stack ?? [],
    free_tier: existing?.free_tier ?? false,
    creates: existing?.creates ?? inferCreates(template),
  }
}

async function refresh() {
  const existingManifest = readManifest()
  validateManifest(existingManifest)
  const existingBySlug = new Map(
    existingManifest.templates.map((template) => [template.slug, template])
  )

  const response = await fetch(getRefreshUrl())
  if (!response.ok) {
    throw new Error(`Failed to fetch Sanity templates: ${response.status} ${response.statusText}`)
  }

  const body = (await response.json()) as { result?: SanityTemplate[]; error?: unknown }
  if (body.error || !Array.isArray(body.result)) {
    throw new Error(`Unexpected Sanity response: ${JSON.stringify(body.error ?? body)}`)
  }

  const refreshed: Manifest = {
    templates: body.result
      .filter((template) => template.slug)
      .map((template) => mergeTemplate(template, existingBySlug.get(template.slug))),
  }

  validateManifest(refreshed)
  writeManifest(refreshed)
  generate(refreshed)
}

async function main() {
  const command = process.argv[2] ?? 'generate'

  if (command === 'generate') {
    generate(readManifest())
    return
  }

  if (command === 'refresh') {
    await refresh()
    return
  }

  throw new Error(`Unknown command "${command}". Use "generate" or "refresh".`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
