import { execFile } from "node:child_process"
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"
import { tmpdir } from "node:os"
import { promisify } from "node:util"
import { afterEach, describe, expect, it } from "vitest"

const exec = promisify(execFile)
const roots: string[] = []
const repo = resolve(".")

afterEach(async () => { await Promise.all(roots.splice(0).map((path) => rm(path, { recursive: true, force: true }))) })

for (const mode of ["npm", "github"] as const) {
  describe(`${mode} installer command`, () => {
    it("installs into the XDG location and preserves existing MCP settings until forced", async () => {
      const root = await mkdtemp(join(tmpdir(), "render-cli-test-")); roots.push(root)
      const target = join(root, "config", "opencode")
      await mkdir(target, { recursive: true })
      const original = { mcp: { render: { enabled: false, type: "remote", url: "https://example.invalid" } } }
      await writeFile(join(target, "opencode.json"), JSON.stringify(original))
      const env = { ...process.env, OPENCODE_CONFIG_DIR: "", XDG_CONFIG_HOME: join(root, "config") }
      const path = join(root, "render-opencode")
      if (mode === "npm") await symlink(join(repo, "dist", "setup.js"), path)
      const command = mode === "npm" ? process.execPath : "bash"
      const args = mode === "npm" ? [path, "setup"] : [join(repo, "install.sh"), "--source", repo]
      await exec(command, [...args, "--enable-mcp"], { env })
      expect(await readFile(join(target, "skills", "render-deploy", "SKILL.md"), "utf8")).toContain("name: render-deploy")
      expect(JSON.parse(await readFile(join(target, "opencode.json"), "utf8"))).toEqual(original)
      await exec(command, [...args, "--enable-mcp", "--force"], { env })
      expect(JSON.parse(await readFile(join(target, "opencode.json"), "utf8")).mcp.render.oauth).toBe(false)
      if (mode === "github") expect(await readFile(join(target, "plugins", "render.ts"), "utf8")).toContain("Generated by npm run build")
    })
  })
}
