import { build } from "esbuild"

// Keep the standalone GitHub entry point in sync with the npm implementation.
await build({
  entryPoints: ["src/index.ts"],
  outfile: "assets/opencode/plugins/render.ts",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "es2022",
  external: ["@opencode-ai/plugin"],
  banner: { js: "// Generated by npm run build from src/index.ts. Do not edit directly." },
})
